### ISSUE TITLE
New method for installing this mod

### ISSUE THREAD

**Issue by Storbie** [rossengeorgiev/dota2mod_manacost#2]
Your Dota 2 mana cost mod is still fully functional in the Reborn client!

I gleaned this method from looking at one of /u/ShutnikMod's newer mods, and so far there's been no problem in this method of installation (from personal testing).

The way it works now:
- The folder that contains mods is now _dota_addons_ (located inside _steamapps\common\dota 2 beta\game_).
- This folder has similar function to the old _custom_ folder, where root directories are created in the folder (e.g. if installing a mod that contains the _resources_ folder, the format should look like _dota 2 beta\game\dota_addons<folder name>\resources_..., where _<folder name>_ can be named anything else).
  - For dota2mod_manacost, the directory to create should be _dota 2 beta\game\dota_addons<folder name>\resource\flash3\images_, then placing the _items_ and _spellicons_ folders inside as normal.
- Afterwards, two launch commands are used: _-enable_addons_ and _-addon <folder name>_ (_<folder name>_ being the folder containing the user's client mods).

/u/ShutnikMod also created a [small video](https://www.youtube.com/watch?v=yx53dBW4JeE) detailing this new method that may also be of use.

I hope this is of some assistance!

**Comment by brlala** [comment]
I saw this reddit comment too linked here
https://www.reddit.com/r/DotA2/comments/3kicsk/found_out_how_to_make_hd_item_icons_mod_work_for/

**Comment by rossengeorgiev** [comment]
Thanks guys, I've updated the instructions and made a release.
