### ISSUE TITLE
update to using mod

### ISSUE THREAD

**Issue by brlala** [rossengeorgiev/dota2mod_manacost#3]
https://www.youtube.com/watch?v=Yfga5IDbPcc
-enable_addons flag is disabled. New way of using mod released by Shutnik. It would be kind of you to upload the description for people who are unaware thank you!

**Comment by rossengeorgiev** [comment]
I will look into it. I don't like the idea of needing to run a executable of unknown source.

**Comment by rossengeorgiev** [comment]
I can get this to work.

**Comment by brlala** [comment]
can't get it to work too. Seems like valve closes all door to addon now :( will let you know when i see other ways of modding
