### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by VetaLioSTV** [rossengeorgiev/dota2mod_manacost#4]
Hello, i have tried much times,but still not work.  
My properties on *_Dota 2 *_
`-console -international -novid -noforcemaccel -noforcemspd -useforcedmparms -high -enable_addons -addon client_mods`
and i'm doing step by step like in TUT(installation) and still nothing.
Whats wrong?

PS Sorry for my eng.

**Comment by rossengeorgiev** [comment]
Hi,
`-enable_addons -addon client_mods` don't work for a long time. I've just updated the page with a different method that seems to work. Just remove those, and delete the client_mods folder. Then follow the steps below

https://github.com/rossengeorgiev/dota2mod_manacost#installation

**Comment by VetaLioSTV** [comment]
@rossengeorgiev Thanks for the fast reply.
As you said

>  I've just updated the page with a different method that seems to work    

there is no update's,seems that remains old version of TUT installation.
BTW i have deleted 
`-enable_addons -addon client_mods`  
from properties and same result, i mean still nothing.
Thanks!

**Comment by rossengeorgiev** [comment]
Follow the steps: https://github.com/rossengeorgiev/dota2mod_manacost#installation

You need to edit a file in step 3.

**Comment by VetaLioSTV** [comment]
@rossengeorgiev it was done at begging.
![image](https://cloud.githubusercontent.com/assets/15155286/14387563/50ebdc2a-fdaa-11e5-9f92-7c2a05652fcb.png)  

tried with all types(manacost/combined/damagetype)!

**Comment by rossengeorgiev** [comment]
Do you have a directory named `costmod_manacost` in `[steam folder]\steamapps\common\dota 2 beta\game\` ?

**Comment by VetaLioSTV** [comment]
@rossengeorgiev nope,doesn't exist

**Comment by rossengeorgiev** [comment]
There's your problem. You need to download and extract `mod_manacost.zip` there. Or any other variation located in the release section.

**Comment by VetaLioSTV** [comment]
@rossengeorgiev My apologize,you're right. All works now. Thank you!
