### ISSUE TITLE
Guides won't load after I edit the gameinfo.gi

### ISSUE THREAD

**Issue by RaPoZaUm** [rossengeorgiev/dota2mod_manacost#5]
The mod works but no guide (item/skill builds) loads after I edit the gameinfo.gi.

**Comment by rossengeorgiev** [comment]
Can't replicate. Everything seems to work fine. Builds occasionally fail unrelated to this mod.

![dddd](https://cloud.githubusercontent.com/assets/2720787/15711893/fef6398c-2807-11e6-850e-85abe07f7c08.png)

**Comment by RaPoZaUm** [comment]
Somehow, the client creates files and a folder inside the mod folder. I'm at work now and can't post pics. Will add later, if it's possible...

Maybe the gameinfo.gi is messed up. That's the only thing I can think of...

**Comment by rossengeorgiev** [comment]
Unless you've done something outside the instructions, I can't see how the mod could break any client functionality. In any case, you could try running `verify game cache` and then install the mod again.

**Comment by RaPoZaUm** [comment]
Sorry for the delay, @rossengeorgiev: I verified cache, it said 1 file to redownload. Games works normally without the mods. I install the mod, same issue (mod shows, guides won't load). The mod folder shows like this:
![costmod_combined folder](https://cloud.githubusercontent.com/assets/19657774/15802796/a2462540-2a95-11e6-98e6-b3030a1460db.png)

I'm only posting this here because I had this mod working perfectly before and am redoing the exact steps (as stated in the installation guide), so, unless it's something I can't realize, it's nothing wrong on my side.

**Comment by rossengeorgiev** [comment]
I encountered the issue, it appears after first run. Probably something to do with guides directory. I don't think there is anything the mod could do to fix that.

**Comment by RaPoZaUm** [comment]
Thanks a lot for taking your time to look at this. Do you think it is fixable?

Let me know if I can do anything to help.

**Comment by RaPoZaUm** [comment]
Oddly enough, guides are loading normally here now. No changes on my client or machine from Jun 4.

Haven't tested on pubs yet, tho. Only on bots game, but it wasn't working there before. I'm confident.
